### PR TITLE
Add an ignore_keys option

### PR DESCRIPTION
**Pull request by djowett-ftw**
Offering this as a parallel to the ignore_fields option (as an alternative to #89). This should help out issues like #86.

### CODE REVIEW

**Comment by canassa** [comment]
@vbabiy I really could use the features implemented by this PR. Is there anything I can do to speed up the merging?

**Comment by vbabiy** [comment]
Let me run through it, and if everything looks good I'll merge it today.

**Comment by canassa** [comment]
Thanks for checking and merging it @vbabiy ! Are you planning a new release anytime soon?

**Comment by vbabiy** [comment]
@canassa 1.4.0 was released on pypi

**Pull request merged**
